import Navbar from "@/components/fragments/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Noto_Serif, Lato } from "next/font/google";
import { Footer } from "@/components/fragments/Footer";

// Konfigurasi font
const notoSerif = Noto_Serif({
  subsets: ["latin"], // Subset karakter
  weight: ["400", "700"], // Berat font
  variable: "--font-noto-serif", // Variabel CSS untuk digunakan di Tailwind
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "E-Katalog | Askha Jaya",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${notoSerif.variable} ${lato.variable}`}>
      <body className={"bg-background overflow-x-hidden"}>
        <header>
          <Navbar />
        </header>
        <main>{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
